# Assingment22_sol

Q1. What are the benefits of the built-in array package, if any?

### sol--> The Array is built-in Python, which only means that you don’t need to download and install it because it comes with native Python.(import array) and it comes with many pre-built methods() like get the size of array shape of array dimension of array ect be can find with only onle line of code by using its pre-built methods or functions().

Q2. What are some of the array package's limitations?

### sol--> Can handle arithmetic operations, must contain all elements of the same size and mostly used in the longer sequence of data elements.

Q3. Describe the main differences between the array and numpy packages.

### sol--> Numpy data structures perform better in size,Performance,Functionality etc.
    Size - Numpy data structures take up less space
    Performance - they have a need for speed and are faster than lists
    Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.

Q4. Explain the distinctions between the empty, ones, and zeros functions.

### sol-->  empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution. Return a new array setting values to zero.
    np.ones([3,3]) --> array([[1., 1., 1.],
                              [1., 1., 1.],
                              [1., 1., 1.]])

    np.zeros([3,3]) --> array([[0., 0., 0.],
                               [0., 0., 0.],
                               [0., 0., 0.]])
    
    np.empty([3,3]) --> array([[0., 0., 0.],
                               [0., 0., 0.],
                               [0., 0., 0.]])

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

### sol--> numpy.fromfunction() function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z).

    np.fromfunction(lambda i,j:i==j,(3,3))
    
    array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])
    

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

### sol--> (A + n) It can add the value of (n) in every element of array (A).
           A=np.ones([2,2]) -->      array([[1., 1.],
                                           [1., 1.]])
                                           
           n=2
           
           A+n -->                   array([[3., 3.],
                                           [3., 3.]])

Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

### sol--> yes It is possible Concatenate can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0. The resulting array after row-wise concatenation is of the shape 6 x 3, i.e. 6 rows and 3 columns.

    np.ones([2,2])+np.ones([2,2]) -->   array([[2., 2.],
                                               [2., 2.]])



    np.ones([2,2])*np.zeros([2,2])  -->   array([[0., 0.],
                                                 [0., 0.]])
    
    
 
Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

### sol--> NumPy arrays have a fixed size at creation, but the length of string is not fixed  unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, so you can not allocate a longer string to one of these arrays.
    
Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

### sol--> When one or more of the arrays to  is a MaskedArray, this function will return a MaskedArray object instead of an ndarray, but the input masks are not preserved.

Q10. What is the best way to use a Boolean array to mask another array?

### sol-->  np.random.random((3,3))<0.5
    array([[0.78131245, 0.79342805, 0.97317221],               array([[False, False, False],        
       [0.83065666, 0.26627861, 0.6664604 ],        -->               [False,  True, False],
       [0.11444078, 0.55676124, 0.67177863]])                         [False, False, False]]) 

Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

### sol--> (1)--stdev() method in Python statistics module. (2)--var = variance(data) ,std_dev = math.sqrt(var).    (3) -- std()  #standard deviation function

    arr=[7, 2, 4, 3, 9, 12, 10, 2]
    std=np.array(arr)
    
    std.std()
    
    import statistics as st
    st.stdev(arr)


    m=st.mean(arr)
    st.stdev(arr, xbar = m)
    
Q12. What is the dimensionality of a Boolean mask-generated array?

### sol--> Through (.ndim)
    x = np.array([1,3,-1, 5, 7, -1]) 
    mask = (x < 0)  
    arr=mask
    arr.ndim  --> 1


In [10]:
#sol1
from array import array

In [13]:
array('u', 'abcdefg')

array('u', 'abcdefg')

In [14]:
arr=array('u', 'abcdefg')

In [15]:
arr

array('u', 'abcdefg')

In [17]:
arr.itemsize

4

In [21]:
arr.typecode

'u'

In [22]:
len(arr)

7

In [23]:
arr.count('f')

1

In [27]:
arr.append('f')

In [28]:
arr.count('f')

2

In [29]:
arr.extend('fff')

In [30]:
arr.count('f')

5

In [31]:
arr

array('u', 'abcdefgffff')

In [32]:
arr.pop()

'f'

In [33]:
arr

array('u', 'abcdefgfff')

In [37]:
arr.reverse()
arr

array('u', 'fffgfedcba')

In [38]:
arr.tolist()

['f', 'f', 'f', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [60]:
#sol4
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.empty([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
#sol5
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [1]:
#sol6
import numpy as np
A=np.ones([2,2])
A

array([[1., 1.],
       [1., 1.]])

In [2]:
n=2
A+=n

In [3]:
A

array([[3., 3.],
       [3., 3.]])

In [5]:
#sol7
np.ones([2,2])+np.ones([2,2])

array([[2., 2.],
       [2., 2.]])

In [7]:
np.ones([2,2])*np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
#sol8
arra=np.array(["i","N","e",'',"u","ro","n"])
arra

array(['i', 'N', 'e', '', 'u', 'ro', 'n'], dtype='<U2')

In [18]:
arra[arra == ''] = 'Hello'
arra

array(['i', 'N', 'e', 'He', 'u', 'ro', 'n'], dtype='<U2')

In [78]:
#sol10
np.random.random((3,3))

array([[0.98594315, 0.54567335, 0.88311443],
       [0.48335678, 0.8145122 , 0.80422092],
       [0.90423484, 0.65365753, 0.38113567]])

In [16]:
np.random.random((3,3))<0.5

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [25]:
#sol 11
arr=[7, 2, 4, 3, 9, 12, 10, 2]
std=np.array(arr)

In [26]:
std.std()

3.6550478793033614

In [29]:
import statistics as st
st.stdev(arr)

3.9074105418879577

In [34]:
m=st.mean(arr)
st.stdev(arr, xbar = m)

3.9074105418879577

In [41]:
#sol 12
x = np.array([1,3,-1, 5, 7, -1]) 
mask = (x < 0)  
arr=mask
arr.ndim

1